src/Entity/ReserveP.php
<?php

namespace App\Entity;

use App\Repository\ReservePRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservePRepository::class)
 */
class ReserveP
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Nom;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;


use App\Repository\ProduitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Request;

class CartController extends AbstractController
{
    /**
     * @Route("/panier", name="cart_index")
     */
    public function index (SessionInterface $session , ProduitsRepository $produitsRepository)
    {
        $panier = $session->get('panier',[]);
        $panierWithData = [];

        foreach($panier as $id => $quantite ){

            $panierWithData[] =[

                'produit'=> $produitsRepository->find($id),
                'quantite'=> $quantite

            ];
        }


        $total =0;
        foreach($panierWithData as $item ){

            $totalItem = $item['produit']->getPrix() * $item['quantite'] ;
            $total +=$totalItem;

        }

        return $this->render('cart/index.html.twig',[
            'items'=> $panierWithData ,
             'total'=> $total
        ]);
    }
    /**
     * @Route("/panier2", name="cart_index2")
     */
    public function index2 (SessionInterface $session , ProduitsRepository $produitsRepository)
    {


        return $this->render('cart/SUCC.html.twig',[

        ]);
    }


    /**
     *  @Route("/panier/add/{id}", name="cart_add")
     */
    public function add($id, SessionInterface $session){
        $panier = $session->get('panier',[]);

        if(!empty( $panier[$id])){

            $panier[$id]++;
        }

        else{

            $panier[$id]=1;
        }


        $session->set('panier', $panier);

        return $this->redirectToRoute("cart_index");

    }

    /**
     *  @Route("/panier/remove/{id}", name="cart_remove")
     */
    public function remove ($id, SessionInterface $session){

        $panier = $session->get('panier',[]);
        if(!empty( $panier[$id])){

            unset($panier[$id]);
        }
        $session->set('panier', $panier);
        return $this->redirectToRoute("cart_index");

    }


}

templates/cart/SUCC.html.twig
{% extends 'base.frontProduitP.html.twig' %}
{% block Produit %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="section-heading">
                <h2>Votre comazeaklzme <em>Trainers</em></h2>
{#                <img src="{{ asset('assets/images/tabs-first-icon') }}" >#}


            </div>
        </div>
    </div>

{% endblock %}

templates/cart/index.html.twig
{% extends 'base.frontProduit.html.twig' %}

{% block title %}Hello CartController!
{% endblock %}

{% block Produit %}
    <div class="bg-light p-3">
        <h1>Votre panier</h1>
    </div>

    {% if items| length >0 %}
        <table class="table">
       <thead>
     <tr>
         <th>Produit</th>
         <th>Prix</th>
         <th>Quantity</th>
         <th>Total</th>
         <th></th>
     </tr>

       </thead>
            <tbody>

            {% for item in items %}
                <tr>
                    <th>{{ item.produit.nom }}</th>
                    <th>{{ item.produit.prix }}</th>
                    <th>{{ item.quantite }}</th>
                    <th>{{ item.produit.prix * item.quantite }}</th>
                    <th>
                        <a class="btn btn-danger btn-sm" href="{{ path('cart_remove' , {'id': item.produit.id }) }}" > Supprimer  </a>


                    </th>
                </tr>

            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th  colspan="3" class="text-right"> Total :</th>
                <th>{{ total }}</th>
                <th></th>

            </tr>

            </tfoot>
        </table>
        <a class="btn btn-info mr-2" style="margin-left:  50%" href="{{ path('produits_index2'  )}} " >Produits</a>
        <a class="btn btn-info mr-2" style="margin-left: 0%" href="{{ path('cart_index2')}} " >commander</a>

    {% else %}
        <p>Surprise, c'est vide !</p>
    {% endif %}


{% endblock %}